#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repository_root="$(cd -- "${script_dir}/.." && pwd)"
site_root="${repository_root}/privacy-site"
privacy_directory="${site_root}/privacy"
privacy_page="${privacy_directory}/index.md"
temporary_privacy=""

cleanup() {
  if [[ -n "${temporary_privacy}" && -f "${temporary_privacy}" ]]; then
    rm -f -- "${temporary_privacy}"
  fi
}

trap cleanup EXIT
umask 022

mkdir -p -- "${privacy_directory}" "${site_root}/assets/project"
temporary_privacy="$(mktemp "${privacy_directory}/.index.XXXXXX")"

{
  printf '%s\n' \
    '---' \
    'layout: default' \
    'title: Privacy notice · 24Seven.FM Player' \
    'description: Understand what the 24Seven.FM Player handles, stores locally, sends to a station, and deliberately does not collect.' \
    'permalink: /privacy/' \
    'section: privacy' \
    '---'
  # The layout supplies the page h1; omit only the source document's duplicate
  # first-line heading while preserving the canonical notice body verbatim.
  sed '1d' "${repository_root}/PRIVACY.md"
} > "${temporary_privacy}"

mv -- "${temporary_privacy}" "${privacy_page}"
temporary_privacy=""
# mktemp creates a private file by default. Jekyll runs inside a container, so
# the generated public source page must be readable by that non-host user.
chmod 644 "${privacy_page}"

# The pages use display-sized copies generated by scripts/build-site-images.py.
# The two full-size files stay because the favicon, manifest, link previews,
# and the tester portal reference them by these names.
cp -- "${repository_root}/docs/play-store-assets/app-icon-512.png" "${site_root}/assets/project/app-icon.png"
cp -- "${repository_root}/docs/play-store-assets/feature-graphic-1024x500.png" "${site_root}/assets/project/feature-graphic.png"
rm -rf -- "${site_root}/assets/project/screenshots" "${site_root}/assets/project/marketing" "${site_root}/assets/project/web"
cp -R -- "${repository_root}/docs/play-store-assets/web" "${site_root}/assets/project/web"

printf 'Prepared the project site source at %s\n' "${site_root}"
